Repository GatorEducator/cellveyor, pull requests merged in 2023-12, with the labels that each got.

#40 Adding test-case for the data.py
  spreadsheets/example_spreadsheet.xlsx
  tests/test_data.py
Labels: test, ready-for-review

#42 Fix Issue Templates Folder Name & Case
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: bug, ready-for-review

#37 Readme
  .mdlrc
  README.md
Labels: documentation, ready-for-review
